version: '3'
services:
  ftp_server:
    container_name: embulk-input-ftp_server
    image: "mcreations/ftp"
    environment:
      - FTP_USER=scott
      - FTP_PASS=tiger
      - HOST=localhost
      - PASV_MIN_PORT=65000
      - PASV_MAX_PORT=65004
    ports:
      - "11021:21"
      - "65000-65004:65000-65004"
    volumes:
      - ./src/test/resources:/data/scott/unittest
